config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources  :users do
    collection do 
      match "import" ,via: [:get, :post]
      get "export"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	require "csv"
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
    	csv << ["name", "email", "telephone_number", "website"]
    	all.each do |user|
      	csv << user.attributes.values_at(*["name", "email", "telephone_number", "website"])
    	end
 		end
	end

	def self.import(file)
		 @arr = []
		 	begin
		 		raise "File type must be csv" if File.extname(file.original_filename) != ".csv"
		 		CSV.foreach(file.path, headers: true) do |row|
			 		if row.to_hash["email"].present? && row.to_hash["name"].present?
			 			row.to_hash["email"].match('^.+@.+$').present? ? create_data(row.to_hash, @arr) : @arr << "#{row.to_hash["email"]} is invalid Email" 
			 		else
			 			@arr << "Insert the name or email for entry"
			 		end
			 	end
    	rescue Exception => e 
    		@arr << e.message
    	end
    	return @arr
  	
	end


	def self.create_data(data,arr)
    unless User.find_by_email(data["email"]).present? 
			User.create! data
		else
			arr << "#{data["email"]} is email has alreay taken"
		end
		return arr
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  require 'csv'
  # require 'iconv'


  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def import
  	if request.get? 
  	else
  		messages = User.import(params[:file])
  		flash[:alert] = messages
  	end
  end

  def export
  	@users = User.all
		respond_to do |format|
		  format.html
		  format.csv { send_data @users.to_csv }
		end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImportExportCsv</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
<div class="alert alert-warning fade in alert-dismissable alert-<%= key %>">
 	<%value.each do |val|%>
  	<%= val %><br/>
  <%end%>
  </div>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/import.html.erb
<%= form_tag import_users_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>
<%= link_to "import", import_users_path %>
<%= link_to "export", export_users_path(format: "csv") %>

<table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Telephone Number</th>
        <th>Website</th>
      </tr>
    </thead>
    <tbody>
			<%@users.each do |u|%>
			<tr>
			<td><%=  u.name %></td>
			<td><%=  u.email %></td>
			<td><%=  u.telephone_number %></td>
			<td><%=  u.website %></td>
			</tr>
			<%end%>
    </tbody>
  </table>